// 150 Pre-seeded authentic confessions across all 5 categories for BajiHears
// Natural Urdu-English mix, concrete emotional details, distributed timestamps & reactions.

import type { Category, Echo, ReactionKey } from "@/shared/types/unsaid";

export interface SeedPost {
  id: string;
  text: string;
  handle: string | null;
  createdAt: number;
  category: Category;
  preset: string;
  reactions: Record<ReactionKey, number>;
  echoes: Echo[];
}

const PRESETS_LIST = ["midnight-static", "3am", "golden-hour", "quiet-storm", "neon-ache"];
const HOUR = 3_600_000;
const now = Date.now();

const r = (heart: number, sad: number, fire: number, hug: number) => ({
  heart,
  sad,
  fire,
  hug,
});

export const SEED_DATA: SeedPost[] = [
  // ==========================================
  // SPILL THE TEA (30 posts)
  // ==========================================
  {
    id: "st-1",
    text: "My cousin is getting married to the guy she swore she ghosted two years ago. I'm literally the only one in the family who knows the real story.",
    handle: "@chaiwala_42",
    createdAt: now - 1 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(28, 4, 18, 12),
    echoes: [
      {
        id: "e-st1",
        text: "Family dawat is about to be a battlefield lol",
        handle: null,
        createdAt: now - 45 * 60_000,
      },
    ],
  },
  {
    id: "st-2",
    text: "I still keep the cinema ticket from that awkward movie date in 2021 inside my passport cover so nobody finds it.",
    handle: null,
    createdAt: now - 2 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(19, 6, 9, 14),
    echoes: [],
  },
  {
    id: "st-3",
    text: "I told my parents I'm doing overtime at the hospital when I'm actually sitting in a car in DHA Phase 6 eating roll paratha in silence.",
    handle: "@raat_ki_baat",
    createdAt: now - 3 * HOUR,
    category: "Spill The Tea",
    preset: "midnight-static",
    reactions: r(45, 2, 38, 22),
    echoes: [
      {
        id: "e-st3-1",
        text: "The peace inside a parked car hits different.",
        handle: "@musafir_99",
        createdAt: now - 2 * HOUR,
      },
      {
        id: "e-st3-2",
        text: "Which roll place though? Red Apple or Hot n Spicy?",
        handle: null,
        createdAt: now - 90 * 60_000,
      },
    ],
  },
  {
    id: "st-4",
    text: "She thinks I deleted her voice notes. I have them backed up on a Google Drive account she doesn't even know exists.",
    handle: null,
    createdAt: now - 3.5 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(34, 15, 12, 18),
    echoes: [],
  },
  {
    id: "st-5",
    text: "I muted our group chat of 7 years because watching everyone plan their destination weddings while I count my savings made me physically sick.",
    handle: "@quietnoise",
    createdAt: now - 4 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(62, 28, 41, 55),
    echoes: [
      {
        id: "e-st5",
        text: "Comparison steals everything, bro. Protect your head.",
        handle: null,
        createdAt: now - 3 * HOUR,
      },
    ],
  },
  {
    id: "st-6",
    text: "I applied for a scholarship abroad just to have an excuse to break up with him without causing a family drama.",
    handle: null,
    createdAt: now - 4.8 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(14, 5, 21, 9),
    echoes: [],
  },
  {
    id: "st-7",
    text: "My rishta aunty told my mom I'm 'a bit too outspoken'. That was the greatest compliment of my entire 24 years of existence.",
    handle: "@bebaak_dil",
    createdAt: now - 5.2 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(88, 3, 72, 30),
    echoes: [
      {
        id: "e-st7",
        text: "Frame that feedback on your wall Queen 👑",
        handle: "@jhalli_07",
        createdAt: now - 4 * HOUR,
      },
    ],
  },
  {
    id: "st-8",
    text: "I saw my ex on Bumble while sitting next to my fiancé choosing sofa covers for our new apartment. My heart did a flip and I hate myself for it.",
    handle: null,
    createdAt: now - 6 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(41, 19, 24, 16),
    echoes: [],
  },
  {
    id: "st-9",
    text: "Everyone thinks I'm confident because I give presentations well. Reality is my hands shake under the podium the entire 15 minutes.",
    handle: "@sheher_ka_poet",
    createdAt: now - 6.5 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(30, 4, 15, 26),
    echoes: [],
  },
  {
    id: "st-10",
    text: "I paid for my friend's birthday dinner and pretended the restaurant had a 50% discount voucher so she wouldn't feel bad.",
    handle: null,
    createdAt: now - 7.2 * HOUR,
    category: "Spill The Tea",
    preset: "midnight-static",
    reactions: r(95, 2, 28, 64),
    echoes: [
      {
        id: "e-st10",
        text: "You are the kind of friend people pray for.",
        handle: null,
        createdAt: now - 6 * HOUR,
      },
    ],
  },
  {
    id: "st-11",
    text: "My brother thinks I forgot his 18th birthday. I've been saving 3k a month from my freelance gig to get him his dream drawing tablet.",
    handle: null,
    createdAt: now - 8 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(54, 1, 19, 42),
    echoes: [],
  },
  {
    id: "st-12",
    text: "I still wear his oversized hoodie when it rains. He took my favourite book and never returned it, so consider it fair trade.",
    handle: "@sukoon_e_dil",
    createdAt: now - 8.5 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(36, 8, 22, 19),
    echoes: [],
  },
  {
    id: "st-13",
    text: "We run a successful startup together and all our investors think we're best friends. We haven't spoken outside of Slack in 8 months.",
    handle: null,
    createdAt: now - 9 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(29, 11, 48, 10),
    echoes: [],
  },
  {
    id: "st-14",
    text: "I unfriended all my high school friends because none of them showed up when my dad was in the ICU. Best boundary I ever set.",
    handle: "@khamoshi_01",
    createdAt: now - 9.7 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(77, 34, 40, 52),
    echoes: [
      {
        id: "e-st14",
        text: "Tough times are the ultimate filter. More power to you.",
        handle: null,
        createdAt: now - 8 * HOUR,
      },
    ],
  },
  {
    id: "st-15",
    text: "I accidentally saw my boss's browser history during a screen share. The imposter syndrome questions he googled made me realize we are all just winging it.",
    handle: null,
    createdAt: now - 10.2 * HOUR,
    category: "Spill The Tea",
    preset: "midnight-static",
    reactions: r(68, 5, 59, 21),
    echoes: [],
  },
  {
    id: "st-16",
    text: "I told my mother I lost my gold earrings so she wouldn't scold me. I actually gave them to my domestic helper whose kid needed surgery.",
    handle: "@dil_ki_awaaz",
    createdAt: now - 11 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(120, 4, 38, 92),
    echoes: [
      {
        id: "e-st16",
        text: "Dil jeet liya yaar. Allah bless you.",
        handle: "@darwesh_77",
        createdAt: now - 9 * HOUR,
      },
    ],
  },
  {
    id: "st-17",
    text: "I accidentally sent 'love you too' to my team lead instead of my mom on WhatsApp. He replied 'noted, please push the PR'. I died.",
    handle: null,
    createdAt: now - 11.5 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(84, 6, 73, 19),
    echoes: [],
  },
  {
    id: "st-18",
    text: "I pretend I hate spicy biryani because the girl I like gets stomach aches from spices and I want us to always share food.",
    handle: "@biryani_lover",
    createdAt: now - 12 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(48, 2, 31, 26),
    echoes: [],
  },
  {
    id: "st-19",
    text: "I saw my best friend's fiancé holding hands with another girl at Packages Mall. I have photos on my phone and I don't know what to do.",
    handle: null,
    createdAt: now - 12.8 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(53, 31, 29, 39),
    echoes: [
      {
        id: "e-st19",
        text: "Tell her immediately. A broken engagement is 100x better than a broken marriage.",
        handle: "@suno_baji",
        createdAt: now - 11 * HOUR,
      },
    ],
  },
  {
    id: "st-20",
    text: "I haven't cooked dinner in three weeks. I just eat leftover chai biscuit and tell my flatmates I ate at the office canteen.",
    handle: null,
    createdAt: now - 13.4 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(24, 18, 11, 35),
    echoes: [],
  },
  {
    id: "st-21",
    text: "My grandfather wrote love poems to a woman who wasn't my grandmother before 1947. I found the notebook in the attic and I can't look at his portrait the same.",
    handle: "@afsana_nigari",
    createdAt: now - 14 * HOUR,
    category: "Spill The Tea",
    preset: "midnight-static",
    reactions: r(67, 24, 33, 44),
    echoes: [],
  },
  {
    id: "st-22",
    text: "I still check her sister's public wedding photos just to catch a blurry glimpse of her in the background.",
    handle: null,
    createdAt: now - 14.6 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(38, 26, 17, 29),
    echoes: [],
  },
  {
    id: "st-23",
    text: "I rejected a high-paying offer in Dubai because my golden retriever is 11 years old and I want to be there for his last days.",
    handle: "@beparwah_dil",
    createdAt: now - 15 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(110, 12, 45, 87),
    echoes: [
      {
        id: "e-st23",
        text: "Money comes and goes, memories with loyal souls don't.",
        handle: null,
        createdAt: now - 13 * HOUR,
      },
    ],
  },
  {
    id: "st-24",
    text: "I told my friends I stopped drinking chai for health reasons. Actually, chai was the only thing I shared with him every evening.",
    handle: null,
    createdAt: now - 15.5 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(27, 21, 9, 31),
    echoes: [],
  },
  {
    id: "st-25",
    text: "I deliberately fail the first round of family card games during Eid so my younger cousins can feel like champions.",
    handle: "@baji_ki_baat",
    createdAt: now - 16 * HOUR,
    category: "Spill The Tea",
    preset: "golden-hour",
    reactions: r(59, 1, 14, 49),
    echoes: [],
  },
  {
    id: "st-26",
    text: "I bought a gym membership six months ago. I've only gone twice, but I still carry the water bottle everywhere like a prop.",
    handle: null,
    createdAt: now - 16.4 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(42, 3, 37, 11),
    echoes: [],
  },
  {
    id: "st-27",
    text: "I got a promotion today and the first person I wanted to call has been married with two kids for four years.",
    handle: null,
    createdAt: now - 17 * HOUR,
    category: "Spill The Tea",
    preset: "3am",
    reactions: r(71, 46, 20, 50),
    echoes: [
      {
        id: "e-st27",
        text: "Congratulations on the promotion. You built that yourself.",
        handle: "@sheher_ka_poet",
        createdAt: now - 15 * HOUR,
      },
    ],
  },
  {
    id: "st-28",
    text: "I borrow books from the library that I already own just to see if someone else made margin notes on my favorite pages.",
    handle: "@vintage_soul",
    createdAt: now - 17.3 * HOUR,
    category: "Spill The Tea",
    preset: "midnight-static",
    reactions: r(33, 4, 18, 25),
    echoes: [],
  },
  {
    id: "st-29",
    text: "I told my relatives I'm preparing for CSS exams so they stop asking when I'm getting married. I'm actually binge-watching crime dramas.",
    handle: null,
    createdAt: now - 17.7 * HOUR,
    category: "Spill The Tea",
    preset: "neon-ache",
    reactions: r(86, 7, 65, 29),
    echoes: [],
  },
  {
    id: "st-30",
    text: "I kept the dry rose petal from the 2018 convocation bouquet. The rose is gone to dust, but the scent in my diary never left.",
    handle: "@sukoon_e_dil",
    createdAt: now - 18 * HOUR,
    category: "Spill The Tea",
    preset: "quiet-storm",
    reactions: r(40, 16, 11, 38),
    echoes: [],
  },

  // ==========================================
  // SILENT THOUGHTS (30 posts)
  // ==========================================
  {
    id: "stt-1",
    text: "Nobody warns you that the hardest part of growing up is realizing your parents were just kids trying to figure it out too.",
    handle: "@khamoshi_01",
    createdAt: now - 1.2 * HOUR,
    category: "Silent Thoughts",
    preset: "midnight-static",
    reactions: r(140, 48, 30, 85),
    echoes: [
      {
        id: "e-stt1",
        text: "Forgiving them was the start of my own peace.",
        handle: null,
        createdAt: now - 50 * 60_000,
      },
    ],
  },
  {
    id: "stt-2",
    text: "I am becoming the exact version of the quiet adult I used to be terrified of when I was sixteen.",
    handle: null,
    createdAt: now - 2.1 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(52, 33, 20, 41),
    echoes: [],
  },
  {
    id: "stt-3",
    text: "Some days the heaviest thing I lift is my own phone to reply to messages that took two seconds to send.",
    handle: "@overthinker_99",
    createdAt: now - 2.8 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(89, 29, 44, 62),
    echoes: [
      {
        id: "e-stt3",
        text: "Social battery is real. Don't feel guilty for needing silence.",
        handle: null,
        createdAt: now - 2 * HOUR,
      },
    ],
  },
  {
    id: "stt-4",
    text: "I miss the version of Lahore that only existed when I was ten and sitting on the scooter between my father and grandfather.",
    handle: null,
    createdAt: now - 3.7 * HOUR,
    category: "Silent Thoughts",
    preset: "golden-hour",
    reactions: r(64, 22, 19, 50),
    echoes: [],
  },
  {
    id: "stt-5",
    text: "We spend our whole youth trying to leave home, and the rest of our lives trying to recreate the smell of our mother's kitchen.",
    handle: "@musafir_99",
    createdAt: now - 4.2 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(115, 38, 25, 78),
    echoes: [
      {
        id: "e-stt5",
        text: "This hit way too close to home in this cold London flat.",
        handle: null,
        createdAt: now - 3 * HOUR,
      },
    ],
  },
  {
    id: "stt-6",
    text: "It is strange how you can share a bed with someone for five years and still feel like you're speaking across a canyon.",
    handle: null,
    createdAt: now - 5 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(48, 36, 12, 45),
    echoes: [],
  },
  {
    id: "stt-7",
    text: "I wonder how many people I have seen for the very last time without either of us knowing it.",
    handle: "@dastan_e_dil",
    createdAt: now - 5.8 * HOUR,
    category: "Silent Thoughts",
    preset: "midnight-static",
    reactions: r(73, 29, 21, 56),
    echoes: [],
  },
  {
    id: "stt-8",
    text: "The silence in my apartment after my guests leave is both the sweetest relief and the sharpest loneliness.",
    handle: null,
    createdAt: now - 6.7 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(37, 19, 14, 30),
    echoes: [],
  },
  {
    id: "stt-9",
    text: "You can forgive someone completely and still never want to sit at the same table with them ever again.",
    handle: "@alfaaz_e_dil",
    createdAt: now - 7.5 * HOUR,
    category: "Silent Thoughts",
    preset: "neon-ache",
    reactions: r(98, 14, 52, 60),
    echoes: [
      {
        id: "e-stt9",
        text: "Forgiveness is about your peace, not their access.",
        handle: "@suno_baji",
        createdAt: now - 6 * HOUR,
      },
    ],
  },
  {
    id: "stt-10",
    text: "I don't think I'm depressed. I think I am just tired of carrying conversations that other people keep dropping.",
    handle: null,
    createdAt: now - 8.2 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(60, 24, 35, 48),
    echoes: [],
  },
  {
    id: "stt-11",
    text: "There is a specific kind of grief in outgrowing the friends who knew you before you had any armor.",
    handle: "@raat_ki_baat",
    createdAt: now - 9.1 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(82, 37, 28, 59),
    echoes: [],
  },
  {
    id: "stt-12",
    text: "I look at old family photo albums and realize that everyone in them was younger than I am right now, pretending to be in control.",
    handle: null,
    createdAt: now - 9.8 * HOUR,
    category: "Silent Thoughts",
    preset: "golden-hour",
    reactions: r(45, 12, 18, 33),
    echoes: [],
  },
  {
    id: "stt-13",
    text: "The hardest conversation you will ever have is admitting to yourself that someone you loved wasn't good for you.",
    handle: "@bebaak_dil",
    createdAt: now - 10.5 * HOUR,
    category: "Silent Thoughts",
    preset: "neon-ache",
    reactions: r(92, 40, 36, 68),
    echoes: [
      {
        id: "e-stt13",
        text: "Took me three years to say this out loud.",
        handle: null,
        createdAt: now - 9 * HOUR,
      },
    ],
  },
  {
    id: "stt-14",
    text: "I still hesitate before typing 'I miss you' because once it's sent, the silence that follows is deafening.",
    handle: null,
    createdAt: now - 11.2 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(66, 31, 15, 42),
    echoes: [],
  },
  {
    id: "stt-15",
    text: "Why do we only realize how happy we were during an ordinary Tuesday three years after that Tuesday is gone?",
    handle: "@shayar_e_shaam",
    createdAt: now - 12.1 * HOUR,
    category: "Silent Thoughts",
    preset: "midnight-static",
    reactions: r(78, 25, 29, 54),
    echoes: [],
  },
  {
    id: "stt-16",
    text: "I bought fresh flowers for my room yesterday not because it was a special occasion, but because I needed proof that something alive is here.",
    handle: null,
    createdAt: now - 12.7 * HOUR,
    category: "Silent Thoughts",
    preset: "golden-hour",
    reactions: r(51, 15, 12, 40),
    echoes: [],
  },
  {
    id: "stt-17",
    text: "You never really get over your first heartbreak; you just build a bigger room around it so you don't bump into it every morning.",
    handle: "@tanhai_ka_safar",
    createdAt: now - 13.5 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(85, 39, 21, 62),
    echoes: [
      {
        id: "e-stt17",
        text: "This metaphor is so painful and accurate.",
        handle: null,
        createdAt: now - 12 * HOUR,
      },
    ],
  },
  {
    id: "stt-18",
    text: "I deleted my social media for a month and not a single person noticed until I missed a WhatsApp birthday greeting.",
    handle: null,
    createdAt: now - 14.1 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(44, 28, 17, 39),
    echoes: [],
  },
  {
    id: "stt-19",
    text: "Healing isn't linear. Last week I felt bulletproof, and today a song in an Uber made me tear up behind my sunglasses.",
    handle: "@sukoon_e_dil",
    createdAt: now - 14.8 * HOUR,
    category: "Silent Thoughts",
    preset: "neon-ache",
    reactions: r(102, 35, 42, 80),
    echoes: [],
  },
  {
    id: "stt-20",
    text: "I wonder if the house I grew up in still remembers the sound of my laughter or if the new owners painted over all of it.",
    handle: null,
    createdAt: now - 15.3 * HOUR,
    category: "Silent Thoughts",
    preset: "golden-hour",
    reactions: r(58, 27, 14, 46),
    echoes: [],
  },
  {
    id: "stt-21",
    text: "Sometimes being the 'strong one' just means you cry in the shower where the running water drowns the sound.",
    handle: "@darwesh_77",
    createdAt: now - 15.9 * HOUR,
    category: "Silent Thoughts",
    preset: "midnight-static",
    reactions: r(90, 42, 26, 75),
    echoes: [
      {
        id: "e-stt21",
        text: "You don't have to carry the whole world today.",
        handle: "@suno_baji",
        createdAt: now - 14 * HOUR,
      },
    ],
  },
  {
    id: "stt-22",
    text: "I re-read old journal entries and felt so proud of that younger me who survived things I thought would kill us.",
    handle: null,
    createdAt: now - 16.3 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(74, 8, 39, 58),
    echoes: [],
  },
  {
    id: "stt-23",
    text: "The strangest feeling is driving through a city where you used to have so many reasons to stop, and now you have none.",
    handle: "@musafir_99",
    createdAt: now - 16.8 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(63, 33, 18, 47),
    echoes: [],
  },
  {
    id: "stt-24",
    text: "I stopped explaining myself when I realized people only understand from their level of perception.",
    handle: null,
    createdAt: now - 17.1 * HOUR,
    category: "Silent Thoughts",
    preset: "neon-ache",
    reactions: r(88, 12, 51, 49),
    echoes: [],
  },
  {
    id: "stt-25",
    text: "I still look for your car at that red light near Liberty Market even though I know you moved to Canada two years ago.",
    handle: "@raat_ki_baat",
    createdAt: now - 17.4 * HOUR,
    category: "Silent Thoughts",
    preset: "midnight-static",
    reactions: r(70, 38, 23, 51),
    echoes: [],
  },
  {
    id: "stt-26",
    text: "Peace of mind is expensive. It costs you a lot of people you thought would be in your corner forever.",
    handle: null,
    createdAt: now - 17.6 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(95, 16, 44, 62),
    echoes: [],
  },
  {
    id: "stt-27",
    text: "I gave so much advice to friends about self-worth while settling for breadcrumbs from someone who barely knew my middle name.",
    handle: "@bebaak_dil",
    createdAt: now - 17.8 * HOUR,
    category: "Silent Thoughts",
    preset: "3am",
    reactions: r(83, 29, 37, 55),
    echoes: [],
  },
  {
    id: "stt-28",
    text: "No one tells you how lonely it gets when you start setting boundaries and the crowd thins out to just your reflection.",
    handle: null,
    createdAt: now - 17.9 * HOUR,
    category: "Silent Thoughts",
    preset: "neon-ache",
    reactions: r(67, 21, 29, 48),
    echoes: [],
  },
  {
    id: "stt-29",
    text: "I keep thinking about that cup of chai we had on that chilly November evening. Neither of us said anything, and yet everything was said.",
    handle: "@chaiwala_42",
    createdAt: now - 18 * HOUR,
    category: "Silent Thoughts",
    preset: "golden-hour",
    reactions: r(55, 17, 19, 43),
    echoes: [],
  },
  {
    id: "stt-30",
    text: "I am slowly learning to love the quiet person I am when nobody is expecting me to perform.",
    handle: "@sukoon_e_dil",
    createdAt: now - 18.2 * HOUR,
    category: "Silent Thoughts",
    preset: "quiet-storm",
    reactions: r(130, 9, 41, 95),
    echoes: [
      {
        id: "e-stt30",
        text: "That is where real freedom lives.",
        handle: null,
        createdAt: now - 17 * HOUR,
      },
    ],
  },

  // ==========================================
  // PLOT TWIST (30 posts)
  // ==========================================
  {
    id: "pt-1",
    text: "The person who ghosted me for three months just applied for a job at my company. Guess who is heading the interview panel tomorrow?",
    handle: "@sheher_ka_poet",
    createdAt: now - 1.5 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(125, 8, 98, 32),
    echoes: [
      {
        id: "e-pt1",
        text: "The universe is petty and I am here for it 🍿",
        handle: "@chaiwala_42",
        createdAt: now - 1 * HOUR,
      },
    ],
  },
  {
    id: "pt-2",
    text: "I spent three years thinking my boss hated my work. Today she promoted me and said 'I pushed you hard because you were the only one with actual talent.'",
    handle: null,
    createdAt: now - 2.4 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(84, 3, 49, 38),
    echoes: [],
  },
  {
    id: "pt-3",
    text: "I accidentally sent my honest critique of a client to the client instead of my colleague. The client replied: 'Finally someone told us the truth, we want to double your contract.'",
    handle: "@beparwah_dil",
    createdAt: now - 3.2 * HOUR,
    category: "Plot Twist",
    preset: "midnight-static",
    reactions: r(110, 4, 85, 29),
    echoes: [],
  },
  {
    id: "pt-4",
    text: "I matched with my therapist's son on Hinge. We both unmatched within 4 seconds without typing a single word.",
    handle: null,
    createdAt: now - 4.1 * HOUR,
    category: "Plot Twist",
    preset: "3am",
    reactions: r(96, 6, 88, 22),
    echoes: [
      {
        id: "e-pt4",
        text: "The next session is going to be cinematic comedy.",
        handle: null,
        createdAt: now - 3 * HOUR,
      },
    ],
  },
  {
    id: "pt-5",
    text: "I got rejected from my dream medical college by 0.2%. Today, six years later, I run a healthcare tech company that employs three of their faculty doctors.",
    handle: "@alfaaz_e_dil",
    createdAt: now - 5.1 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(145, 2, 110, 60),
    echoes: [
      {
        id: "e-pt5",
        text: "Rejection is just redirection on a grander scale.",
        handle: "@suno_baji",
        createdAt: now - 4 * HOUR,
      },
    ],
  },
  {
    id: "pt-6",
    text: "I ordered food for one and the delivery guy said 'Cheer up baji, bad days don't last forever.' How did he know I had been crying all afternoon?",
    handle: null,
    createdAt: now - 6.2 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(91, 14, 25, 76),
    echoes: [],
  },
  {
    id: "pt-7",
    text: "I blocked him on WhatsApp, Instagram, and LinkedIn. He literally transferred 10 rupees on EasyPaisa with a message in the transaction note.",
    handle: "@jhalli_07",
    createdAt: now - 7 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(132, 11, 105, 34),
    echoes: [
      {
        id: "e-pt7",
        text: "EasyPaisa stalking is a different tax bracket of unhinged 😭",
        handle: null,
        createdAt: now - 5 * HOUR,
      },
    ],
  },
  {
    id: "pt-8",
    text: "I hated him for five years for breaking my heart. Today I saw who he turned out to be and thanked God on my prayer mat for sparing me.",
    handle: null,
    createdAt: now - 7.9 * HOUR,
    category: "Plot Twist",
    preset: "quiet-storm",
    reactions: r(118, 9, 64, 55),
    echoes: [],
  },
  {
    id: "pt-9",
    text: "I took a wrong turn in Islamabad and ended up at a viewpoint I never knew existed. Met someone there reading the exact same obscure Urdu poetry book.",
    handle: "@musafir_99",
    createdAt: now - 8.7 * HOUR,
    category: "Plot Twist",
    preset: "midnight-static",
    reactions: r(72, 3, 31, 48),
    echoes: [],
  },
  {
    id: "pt-10",
    text: "The person I used to fight with the most in school is now the godparent of my daughter and the only person I trust with my life.",
    handle: null,
    createdAt: now - 9.5 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(65, 4, 28, 52),
    echoes: [],
  },
  {
    id: "pt-11",
    text: "I accidentally liked a post from 2017 while cyber-stalking my crush at 3 AM. He DM'd me 2 minutes later: 'I was looking at your 2017 photos too.'",
    handle: "@raat_ki_baat",
    createdAt: now - 10.3 * HOUR,
    category: "Plot Twist",
    preset: "3am",
    reactions: r(140, 5, 115, 45),
    echoes: [
      {
        id: "e-pt11",
        text: "Wedding card when?!",
        handle: "@chaiwala_42",
        createdAt: now - 8 * HOUR,
      },
    ],
  },
  {
    id: "pt-12",
    text: "I thought I lost my grandma's recipe notebook when we shifted houses. Found it ten years later tucked inside an old Quran cover.",
    handle: null,
    createdAt: now - 11.1 * HOUR,
    category: "Plot Twist",
    preset: "quiet-storm",
    reactions: r(80, 7, 22, 63),
    echoes: [],
  },
  {
    id: "pt-13",
    text: "My fiancé and I discovered our grandfathers were cellmates in prison during the 1970 political protests. Our marriage was written 50 years ago.",
    handle: "@dastan_e_dil",
    createdAt: now - 11.9 * HOUR,
    category: "Plot Twist",
    preset: "midnight-static",
    reactions: r(105, 6, 48, 70),
    echoes: [],
  },
  {
    id: "pt-14",
    text: "I resigned from my toxic corporate job with zero backup savings. Three days later, a company I interviewed at 8 months ago called with an offer 2x higher.",
    handle: null,
    createdAt: now - 12.6 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(122, 3, 77, 58),
    echoes: [],
  },
  {
    id: "pt-15",
    text: "I pretended to know how to play chess on a first date. Won the match in four moves by sheer blind luck and now I have to keep this lie going.",
    handle: "@pagal_sa_dil",
    createdAt: now - 13.2 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(88, 4, 62, 25),
    echoes: [],
  },
  {
    id: "pt-16",
    text: "I spent months trying to find who was leaving anonymous encouraging notes on my car windshield in the office parking. It was the security guard uncle.",
    handle: null,
    createdAt: now - 13.9 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(115, 6, 34, 94),
    echoes: [
      {
        id: "e-pt16",
        text: "Give that uncle a huge Eid bonus and a hug!",
        handle: null,
        createdAt: now - 12 * HOUR,
      },
    ],
  },
  {
    id: "pt-17",
    text: "The rishta aunty rejected me for 'being too modern'. Two years later her own daughter hired my digital marketing agency to rebrand her clothing line.",
    handle: "@bebaak_dil",
    createdAt: now - 14.5 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(138, 5, 102, 40),
    echoes: [],
  },
  {
    id: "pt-18",
    text: "I thought my husband forgot our anniversary today. He brought home an adoption certificate for the stray cat I had been feeding for six months.",
    handle: null,
    createdAt: now - 15.1 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(95, 2, 36, 88),
    echoes: [],
  },
  {
    id: "pt-19",
    text: "I threw away a lottery ticket thinking I won nothing. My little sister picked it out of the bin and won 50,000 rupees.",
    handle: null,
    createdAt: now - 15.7 * HOUR,
    category: "Plot Twist",
    preset: "midnight-static",
    reactions: r(74, 18, 55, 22),
    echoes: [],
  },
  {
    id: "pt-20",
    text: "The person who gave me the worst heartbreak of my life is also the sole reason I discovered my passion for writing. I am grateful and bitter at the same time.",
    handle: "@sheher_ka_poet",
    createdAt: now - 16.2 * HOUR,
    category: "Plot Twist",
    preset: "quiet-storm",
    reactions: r(84, 21, 38, 51),
    echoes: [],
  },
  {
    id: "pt-21",
    text: "I told my strict father I don't want to take over the family business. Instead of shouting, he sighed, smiled, and said 'I was hoping you'd have the guts to say that.'",
    handle: null,
    createdAt: now - 16.7 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(112, 8, 45, 79),
    echoes: [],
  },
  {
    id: "pt-22",
    text: "I went to a blind date arranged by my aunt and it turned out to be my university lab partner from 2019 who I had a silent crush on for three semesters.",
    handle: "@sukoon_e_dil",
    createdAt: now - 17.1 * HOUR,
    category: "Plot Twist",
    preset: "3am",
    reactions: r(126, 3, 68, 64),
    echoes: [
      {
        id: "e-pt22",
        text: "God really said: 'take two, roll camera!'",
        handle: "@suno_baji",
        createdAt: now - 15 * HOUR,
      },
    ],
  },
  {
    id: "pt-23",
    text: "I bought a cheap old painting from Sunday Bazaar for 500 rupees. Turned out the wooden backing had two vintage silver coins from 1932 hidden inside.",
    handle: null,
    createdAt: now - 17.4 * HOUR,
    category: "Plot Twist",
    preset: "midnight-static",
    reactions: r(69, 2, 40, 28),
    echoes: [],
  },
  {
    id: "pt-24",
    text: "I sent a voice note venting about my cousin to my cousin. Quickest delete-for-everyone in human history, but the damage was already felt in my soul.",
    handle: "@jhalli_07",
    createdAt: now - 17.6 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(98, 26, 70, 31),
    echoes: [],
  },
  {
    id: "pt-25",
    text: "I spent three years thinking my dog preferred my dad. When I got sick with dengue, that dog slept on my shoes by the door and didn't move for four days.",
    handle: null,
    createdAt: now - 17.8 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(104, 11, 29, 90),
    echoes: [],
  },
  {
    id: "pt-26",
    text: "I thought my friend was ignoring my calls because she was mad at me. She was secretly organizing a 15-person surprise reunion for my birthday.",
    handle: null,
    createdAt: now - 17.9 * HOUR,
    category: "Plot Twist",
    preset: "quiet-storm",
    reactions: r(77, 4, 32, 59),
    echoes: [],
  },
  {
    id: "pt-27",
    text: "I applied to an art competition using a fake name because I was embarrassed of my sketches. I won 2nd prize and had to reveal my identity to claim the trophy.",
    handle: "@vintage_soul",
    createdAt: now - 18 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(88, 3, 54, 42),
    echoes: [],
  },
  {
    id: "pt-28",
    text: "I thought my quiet coworker was shy. Today at karaoke she took the mic and delivered an operatic performance that silenced the entire lounge.",
    handle: null,
    createdAt: now - 18.1 * HOUR,
    category: "Plot Twist",
    preset: "golden-hour",
    reactions: r(63, 1, 48, 20),
    echoes: [],
  },
  {
    id: "pt-29",
    text: "I found a handwritten letter from my mother to my father from 1989. She was complaining about his bad driving even before they were married.",
    handle: "@raat_ki_baat",
    createdAt: now - 18.2 * HOUR,
    category: "Plot Twist",
    preset: "quiet-storm",
    reactions: r(85, 3, 35, 52),
    echoes: [],
  },
  {
    id: "pt-30",
    text: "I promised myself I would never fall in love again after 2022. Then someone handed me half a samosa in a rainstorm and ruined my whole villain arc.",
    handle: "@chaiwala_42",
    createdAt: now - 18.3 * HOUR,
    category: "Plot Twist",
    preset: "neon-ache",
    reactions: r(150, 4, 95, 72),
    echoes: [
      {
        id: "e-pt30",
        text: "Food love is the purest form of surrender 🥟",
        handle: null,
        createdAt: now - 16 * HOUR,
      },
    ],
  },

  // ==========================================
  // HARD TRUTH (30 posts)
  // ==========================================
  {
    id: "ht-1",
    text: "You can love someone with every fiber of your being and still realize that building a life with them would destroy your peace.",
    handle: "@alfaaz_e_dil",
    createdAt: now - 1.1 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(160, 42, 55, 95),
    echoes: [
      {
        id: "e-ht1",
        text: "Love is never enough on its own. Compatibility and respect are non-negotiable.",
        handle: "@suno_baji",
        createdAt: now - 45 * 60_000,
      },
    ],
  },
  {
    id: "ht-2",
    text: "If you have to rehearse every sentence in your head before texting them so they don't misunderstand or get angry, that's not love. That's walking on eggshells.",
    handle: null,
    createdAt: now - 2 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(135, 38, 70, 80),
    echoes: [],
  },
  {
    id: "ht-3",
    text: "Being the bigger person every single time doesn't make you mature; it just teaches toxic people how much they can get away with.",
    handle: "@bebaak_dil",
    createdAt: now - 2.9 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(148, 15, 92, 68),
    echoes: [
      {
        id: "e-ht3",
        text: "Say it louder for everyone in Asian families!",
        handle: "@jhalli_07",
        createdAt: now - 2 * HOUR,
      },
    ],
  },
  {
    id: "ht-4",
    text: "Half the people who tell you to 'have sabr' are just uncomfortable with your anger because it forces them to confront their own passivity.",
    handle: null,
    createdAt: now - 3.8 * HOUR,
    category: "Hard Truth",
    preset: "midnight-static",
    reactions: r(112, 19, 81, 49),
    echoes: [],
  },
  {
    id: "ht-5",
    text: "Your twenties are not meant to be a constant highlight reel. Most of it is just unglamorous budgeting, cleaning your room, and learning to sit with your thoughts.",
    handle: "@sheher_ka_poet",
    createdAt: now - 4.6 * HOUR,
    category: "Hard Truth",
    preset: "golden-hour",
    reactions: r(95, 11, 48, 62),
    echoes: [],
  },
  {
    id: "ht-6",
    text: "Staying in a dead relationship because 'we've invested five years' is like continuing in the wrong direction because you already bought the bus ticket.",
    handle: null,
    createdAt: now - 5.5 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(128, 29, 65, 74),
    echoes: [
      {
        id: "e-ht6",
        text: "Sunk cost fallacy in relationships is the biggest life waster.",
        handle: null,
        createdAt: now - 4 * HOUR,
      },
    ],
  },
  {
    id: "ht-7",
    text: "Nobody is 'too busy'. If you matter to them, they make the time. If you don't, they make excuses. It really is that brutally simple.",
    handle: "@raat_ki_baat",
    createdAt: now - 6.3 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(170, 45, 90, 85),
    echoes: [],
  },
  {
    id: "ht-8",
    text: "Sometimes you aren't fighting for the relationship; you're just fighting to avoid the shame of failing in front of relatives.",
    handle: null,
    createdAt: now - 7.1 * HOUR,
    category: "Hard Truth",
    preset: "midnight-static",
    reactions: r(104, 33, 52, 60),
    echoes: [],
  },
  {
    id: "ht-9",
    text: "You cannot heal in the same environment that made you sick. As long as you keep opening the door for them, your wound stays fresh.",
    handle: "@darwesh_77",
    createdAt: now - 8 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(140, 28, 75, 90),
    echoes: [],
  },
  {
    id: "ht-10",
    text: "Most people don't listen to understand; they listen to reply, deflect, or defend themselves. True listeners are rare as gold.",
    handle: null,
    createdAt: now - 8.8 * HOUR,
    category: "Hard Truth",
    preset: "golden-hour",
    reactions: r(88, 12, 45, 58),
    echoes: [],
  },
  {
    id: "ht-11",
    text: "An apology without changed behavior is just manipulation wrapped in good manners.",
    handle: "@bebaak_dil",
    createdAt: now - 9.6 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(155, 18, 98, 70),
    echoes: [
      {
        id: "e-ht11",
        text: "Memorize this line, ladies and gentlemen.",
        handle: "@chaiwala_42",
        createdAt: now - 8 * HOUR,
      },
    ],
  },
  {
    id: "ht-12",
    text: "You are not responsible for fixing someone whose broken pieces keep cutting your hands.",
    handle: null,
    createdAt: now - 10.4 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(132, 34, 60, 88),
    echoes: [],
  },
  {
    id: "ht-13",
    text: "Money doesn't buy happiness, but poverty brings a specific, suffocating brand of daily anxiety that poisons every single relationship.",
    handle: "@musafir_99",
    createdAt: now - 11.3 * HOUR,
    category: "Hard Truth",
    preset: "midnight-static",
    reactions: r(119, 21, 74, 52),
    echoes: [],
  },
  {
    id: "ht-14",
    text: "The reason you attract emotionally unavailable people is because deep down, you're terrified of real intimacy yourself.",
    handle: null,
    createdAt: now - 12 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(98, 30, 48, 59),
    echoes: [],
  },
  {
    id: "ht-15",
    text: "Family loyalty that demands you sacrifice your mental sanity isn't loyalty; it is generational blackmail.",
    handle: "@alfaaz_e_dil",
    createdAt: now - 12.8 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(165, 27, 105, 82),
    echoes: [
      {
        id: "e-ht15",
        text: "Breaking generational curses hurts, but future generations will thank you.",
        handle: "@suno_baji",
        createdAt: now - 11 * HOUR,
      },
    ],
  },
  {
    id: "ht-16",
    text: "If you constantly have to remind someone to treat you with basic kindness, they are not forgetful — they just don't care.",
    handle: null,
    createdAt: now - 13.6 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(120, 31, 62, 70),
    echoes: [],
  },
  {
    id: "ht-17",
    text: "A lot of people love the idea of you, but the minute you stop being convenient for their lifestyle, the love vanishes.",
    handle: "@khamoshi_01",
    createdAt: now - 14.2 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(94, 25, 41, 58),
    echoes: [],
  },
  {
    id: "ht-18",
    text: "You can be the sweetest peach on the tree, and there will still be people who simply dislike peaches. Stop trying to convert everyone.",
    handle: null,
    createdAt: now - 14.9 * HOUR,
    category: "Hard Truth",
    preset: "golden-hour",
    reactions: r(86, 6, 38, 50),
    echoes: [],
  },
  {
    id: "ht-19",
    text: "Closure doesn't come from their final explanation. Closure comes when you accept that they will never give you the answers you deserve.",
    handle: "@sukoon_e_dil",
    createdAt: now - 15.4 * HOUR,
    category: "Hard Truth",
    preset: "midnight-static",
    reactions: r(138, 32, 59, 85),
    echoes: [],
  },
  {
    id: "pt-20-ht",
    text: "Self-care isn't just scented candles and sheet masks. Real self-care is having uncomfortable conversations, paying bills on time, and going to sleep before 1 AM.",
    handle: null,
    createdAt: now - 15.8 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(108, 8, 64, 55),
    echoes: [],
  },
  {
    id: "ht-21",
    text: "The person who hurt you will rarely feel the depth of pain they caused. Stop waiting for their revelation; heal for yourself.",
    handle: "@sheher_ka_poet",
    createdAt: now - 16.3 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(126, 36, 50, 78),
    echoes: [],
  },
  {
    id: "ht-22",
    text: "Overthinking is just a polite word for not trusting that you will survive if things go wrong.",
    handle: null,
    createdAt: now - 16.8 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(91, 19, 43, 62),
    echoes: [],
  },
  {
    id: "ht-23",
    text: "Your intuition warned you the first week. You just called it 'overreacting' because you wanted the fairy tale so badly.",
    handle: "@bebaak_dil",
    createdAt: now - 17.1 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(142, 28, 88, 70),
    echoes: [
      {
        id: "e-ht23",
        text: "The gut never lies. The heart just makes excuses.",
        handle: null,
        createdAt: now - 15 * HOUR,
      },
    ],
  },
  {
    id: "ht-24",
    text: "Not every friendship is meant for lifelong duration. Some people are just seasons meant to teach you what you will never tolerate again.",
    handle: null,
    createdAt: now - 17.4 * HOUR,
    category: "Hard Truth",
    preset: "golden-hour",
    reactions: r(79, 14, 33, 51),
    echoes: [],
  },
  {
    id: "ht-25",
    text: "Stop sharing your deepest dreams with people who have never stepped outside their own comfort zone.",
    handle: "@musafir_99",
    createdAt: now - 17.6 * HOUR,
    category: "Hard Truth",
    preset: "midnight-static",
    reactions: r(99, 5, 60, 48),
    echoes: [],
  },
  {
    id: "ht-26",
    text: "You don't need a revenge plan. People who treat others poorly always end up creating their own private hell eventually.",
    handle: null,
    createdAt: now - 17.8 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(115, 11, 68, 64),
    echoes: [],
  },
  {
    id: "ht-27",
    text: "Validation from strangers on the internet will never patch the hole left by parents who never looked you in the eye and said 'I'm proud of you.'",
    handle: "@raat_ki_baat",
    createdAt: now - 18 * HOUR,
    category: "Hard Truth",
    preset: "3am",
    reactions: r(130, 40, 52, 79),
    echoes: [],
  },
  {
    id: "ht-28",
    text: "Hard work does not guarantee success. Timing, privilege, health, and luck play massive roles. Acknowledge your blessings and have empathy.",
    handle: null,
    createdAt: now - 18.1 * HOUR,
    category: "Hard Truth",
    preset: "golden-hour",
    reactions: r(87, 8, 41, 56),
    echoes: [],
  },
  {
    id: "ht-29",
    text: "If they wanted to, they would. Five words that will save you months of sleepless nights and embarrassing over-analyzing.",
    handle: "@jhalli_07",
    createdAt: now - 18.2 * HOUR,
    category: "Hard Truth",
    preset: "neon-ache",
    reactions: r(152, 22, 94, 76),
    echoes: [],
  },
  {
    id: "ht-30",
    text: "The person you need to forgive most for all the wasted time, bad decisions, and broken boundaries is yourself.",
    handle: "@sukoon_e_dil",
    createdAt: now - 18.3 * HOUR,
    category: "Hard Truth",
    preset: "quiet-storm",
    reactions: r(175, 30, 65, 110),
    echoes: [
      {
        id: "e-ht30",
        text: "Take a deep breath. You survived. Be gentle with yourself today.",
        handle: "@suno_baji",
        createdAt: now - 16 * HOUR,
      },
    ],
  },

  // ==========================================
  // VIBE CHECK (30 posts)
  // ==========================================
  {
    id: "vc-1",
    text: "Current vibe: drinking cardamom tea in a slightly oversized cardigan while listening to 90s Coke Studio and pretending responsibilities don't exist.",
    handle: "@chaiwala_42",
    createdAt: now - 1.3 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(110, 2, 45, 68),
    echoes: [
      {
        id: "e-vc1",
        text: "Add some rain on the window and it is heaven on earth.",
        handle: null,
        createdAt: now - 50 * 60_000,
      },
    ],
  },
  {
    id: "vc-2",
    text: "Unpopular opinion: eating cold leftover biryani straight out of the fridge at 2:30 AM with a tablespoon hits harder than any fancy fine dining.",
    handle: "@biryani_lover",
    createdAt: now - 2.2 * HOUR,
    category: "Vibe Check",
    preset: "3am",
    reactions: r(140, 3, 112, 38),
    echoes: [
      {
        id: "e-vc2",
        text: "This is not an unpopular opinion, this is spiritual enlightenment.",
        handle: "@jhalli_07",
        createdAt: now - 90 * 60_000,
      },
    ],
  },
  {
    id: "vc-3",
    text: "Normalize canceling plans 2 hours before just because your bed feels extra cozy and the weather is too moody to leave the house.",
    handle: null,
    createdAt: now - 3.1 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(92, 6, 38, 54),
    echoes: [],
  },
  {
    id: "vc-4",
    text: "That feeling when you put on a song you haven't heard in six years and your muscles instantly remember how you felt back in college.",
    handle: "@vintage_soul",
    createdAt: now - 3.9 * HOUR,
    category: "Vibe Check",
    preset: "midnight-static",
    reactions: r(85, 9, 31, 49),
    echoes: [],
  },
  {
    id: "vc-5",
    text: "The sheer therapeutic power of cleaning your entire room, taking a warm shower, and getting into crisp bedsheets with zero alarms set for tomorrow.",
    handle: "@sukoon_e_dil",
    createdAt: now - 4.9 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(155, 1, 58, 89),
    echoes: [],
  },
  {
    id: "vc-6",
    text: "Is it just me or does driving on the Ring Road with windows slightly down at midnight solve at least 40% of all life problems?",
    handle: "@musafir_99",
    createdAt: now - 5.7 * HOUR,
    category: "Vibe Check",
    preset: "neon-ache",
    reactions: r(118, 4, 82, 45),
    echoes: [],
  },
  {
    id: "vc-7",
    text: "My favorite genre of human is people who send you memes with zero context and expect you to laugh without saying 'hi how are you'.",
    handle: null,
    createdAt: now - 6.6 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(125, 2, 75, 52),
    echoes: [
      {
        id: "e-vc7",
        text: "Low-maintenance friendships are the best friendships.",
        handle: "@chaiwala_42",
        createdAt: now - 5 * HOUR,
      },
    ],
  },
  {
    id: "vc-8",
    text: "That very first sip of water when you wake up parched at 4 AM is tastier than any drink ever invented by humanity.",
    handle: null,
    createdAt: now - 7.4 * HOUR,
    category: "Vibe Check",
    preset: "3am",
    reactions: r(78, 1, 41, 30),
    echoes: [],
  },
  {
    id: "vc-9",
    text: "Finding a 1,000 rupee note in your winter jacket pocket that you forgot about since last year feels like winning the Nobel Prize.",
    handle: "@jhalli_07",
    createdAt: now - 8.3 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(134, 2, 89, 40),
    echoes: [],
  },
  {
    id: "vc-10",
    text: "I judge restaurants purely based on the temperature and crunch of their complementary mint raita.",
    handle: null,
    createdAt: now - 9.2 * HOUR,
    category: "Vibe Check",
    preset: "neon-ache",
    reactions: r(67, 3, 44, 21),
    echoes: [],
  },
  {
    id: "vc-11",
    text: "The smell of wet soil right after the first monsoon shower in July should be bottled and sold as pure emotional healing.",
    handle: "@sheher_ka_poet",
    createdAt: now - 10.1 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(142, 3, 50, 80),
    echoes: [
      {
        id: "e-vc11",
        text: "Mitti ki khushbu is our national antidepressant.",
        handle: null,
        createdAt: now - 8 * HOUR,
      },
    ],
  },
  {
    id: "vc-12",
    text: "Sitting in an outdoor dhaba late at night when the waiter brings doodh patti in a cracked cup and nobody is on their phones. Real wealth.",
    handle: "@darwesh_77",
    createdAt: now - 10.9 * HOUR,
    category: "Vibe Check",
    preset: "midnight-static",
    reactions: r(128, 4, 62, 74),
    echoes: [],
  },
  {
    id: "vc-13",
    text: "My personal red flag: I will research a 200 rupee purchase for two weeks, but book a 15,000 rupee spontaneous road trip in 3 minutes.",
    handle: null,
    createdAt: now - 11.7 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(102, 5, 73, 31),
    echoes: [],
  },
  {
    id: "vc-14",
    text: "Watching the sun rise from a train window with cold air rushing through the door gap while chai vendors shout outside. Peak aesthetic.",
    handle: "@musafir_99",
    createdAt: now - 12.4 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(115, 6, 39, 68),
    echoes: [],
  },
  {
    id: "vc-15",
    text: "Anyone else have that one hoodie that is objectively ugly and faded, but it contains 90% of your comfort in this universe?",
    handle: null,
    createdAt: now - 13.1 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(98, 2, 54, 59),
    echoes: [],
  },
  {
    id: "vc-16",
    text: "The satisfaction of unsubscribing from promotional marketing emails that have been cluttering your inbox since 2018.",
    handle: "@bebaak_dil",
    createdAt: now - 13.8 * HOUR,
    category: "Vibe Check",
    preset: "neon-ache",
    reactions: r(84, 1, 48, 26),
    echoes: [],
  },
  {
    id: "vc-17",
    text: "I love people who get genuinely excited over small things like finding a cool leaf, seeing a cute street cat, or eating a hot jalebi.",
    handle: "@sukoon_e_dil",
    createdAt: now - 14.4 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(135, 2, 43, 91),
    echoes: [
      {
        id: "e-vc17",
        text: "Childlike wonder in adults is the most attractive trait.",
        handle: "@suno_baji",
        createdAt: now - 12 * HOUR,
      },
    ],
  },
  {
    id: "vc-18",
    text: "Nothing beats the silence of an empty office after 7 PM when you can play your playlist out loud on speakers.",
    handle: null,
    createdAt: now - 15 * HOUR,
    category: "Vibe Check",
    preset: "midnight-static",
    reactions: r(72, 3, 35, 30),
    echoes: [],
  },
  {
    id: "vc-19",
    text: "A good book, a balcony facing trees, a cup of Kashmiri chai, and zero unread notifications. That is my entire retirement plan.",
    handle: "@vintage_soul",
    createdAt: now - 15.6 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(140, 2, 49, 85),
    echoes: [],
  },
  {
    id: "vc-20",
    text: "People who text 'let me know when you reach home safe' deserve all the good things life has to offer.",
    handle: null,
    createdAt: now - 16.1 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(160, 4, 52, 102),
    echoes: [],
  },
  {
    id: "vc-21",
    text: "The energy of walking into a bookshop with wooden shelves, low lighting, and that specific paper smell is unmatched.",
    handle: "@sheher_ka_poet",
    createdAt: now - 16.5 * HOUR,
    category: "Vibe Check",
    preset: "midnight-static",
    reactions: r(93, 1, 38, 54),
    echoes: [],
  },
  {
    id: "vc-22",
    text: "Life is too short to drink mediocre instant coffee or pretend you like people who talk over everyone at dinner.",
    handle: null,
    createdAt: now - 16.9 * HOUR,
    category: "Vibe Check",
    preset: "neon-ache",
    reactions: r(105, 3, 67, 45),
    echoes: [],
  },
  {
    id: "vc-23",
    text: "The unspoken bond between strangers who make eye contact and smile when a little baby does something goofy in the grocery line.",
    handle: "@alfaaz_e_dil",
    createdAt: now - 17.2 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(112, 1, 34, 75),
    echoes: [],
  },
  {
    id: "vc-24",
    text: "Entering your clean room after a 14-hour workday and just collapsing face-down on the mattress without taking your shoes off for 5 minutes.",
    handle: null,
    createdAt: now - 17.5 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(88, 5, 42, 60),
    echoes: [],
  },
  {
    id: "vc-25",
    text: "Listening to Nusrat Fateh Ali Khan on full volume during a night highway drive while watching truck art reflect in your headlights.",
    handle: "@darwesh_77",
    createdAt: now - 17.7 * HOUR,
    category: "Vibe Check",
    preset: "midnight-static",
    reactions: r(130, 4, 95, 58),
    echoes: [],
  },
  {
    id: "vc-26",
    text: "I am in my soft season: drinking water, minding my own business, avoiding arguments, and keeping my circle smaller than a coin.",
    handle: "@sukoon_e_dil",
    createdAt: now - 17.9 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(145, 2, 59, 90),
    echoes: [],
  },
  {
    id: "vc-27",
    text: "When the barber or salon girl washes your hair with that slightly too warm water and starts the scalp massage... pure bliss.",
    handle: null,
    createdAt: now - 18 * HOUR,
    category: "Vibe Check",
    preset: "3am",
    reactions: r(96, 1, 48, 38),
    echoes: [],
  },
  {
    id: "vc-28",
    text: "That brief moment during winter sunsets when the sky turns a shade of dusty violet and everyone on the street looks like poetry.",
    handle: "@vintage_soul",
    createdAt: now - 18.1 * HOUR,
    category: "Vibe Check",
    preset: "quiet-storm",
    reactions: r(122, 2, 44, 72),
    echoes: [],
  },
  {
    id: "vc-29",
    text: "I rate my days not by productivity anymore, but by how many genuine laughs I shared and how good my evening chai tasted.",
    handle: "@chaiwala_42",
    createdAt: now - 18.2 * HOUR,
    category: "Vibe Check",
    preset: "golden-hour",
    reactions: r(138, 2, 51, 88),
    echoes: [
      {
        id: "e-vc29",
        text: "The healthiest metric out there.",
        handle: null,
        createdAt: now - 16 * HOUR,
      },
    ],
  },
  {
    id: "vc-30",
    text: "To whoever is reading this at 2 AM: put your phone down, drink a glass of water, and get some rest. Tomorrow is a fresh page.",
    handle: "@suno_baji",
    createdAt: now - 18.3 * HOUR,
    category: "Vibe Check",
    preset: "3am",
    reactions: r(190, 8, 70, 140),
    echoes: [
      {
        id: "e-vc30",
        text: "Needed this reminder tonight. Goodnight Baji 🌙",
        handle: "@raat_ki_baat",
        createdAt: now - 15 * HOUR,
      },
    ],
  },
];
