/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CornerRouteImport } from './routes/corner'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as ReadRouteImport } from './routes/read'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CornerRoute = CornerRouteImport.update({
  id: '/corner',
  path: '/corner',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corner': typeof CornerRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/duel': typeof DuelRoute
  '/read': typeof ReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corner': typeof CornerRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/duel': typeof DuelRoute
  '/read': typeof ReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corner': typeof CornerRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/duel': typeof DuelRoute
  '/read': typeof ReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/corner' | '/diagnostics' | '/duel' | '/read'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corner' | '/diagnostics' | '/duel' | '/read'
  id: '__root__' | '/' | '/corner' | '/diagnostics' | '/duel' | '/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CornerRoute: typeof CornerRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DuelRoute: typeof DuelRoute
  ReadRoute: typeof ReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corner': {
      id: '/corner'
      path: '/corner'
      fullPath: '/corner'
      preLoaderRoute: typeof CornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CornerRoute: CornerRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DuelRoute: DuelRoute,
  ReadRoute: ReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
